### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by richardcrichardc** [paulmelnikow/ObjCBSON#1]
It would be helpful to mention in the docs that automake and libtool are dependencies.

I don't know if cocoapods can help with those. I used brew to install these.

**Comment by paulmelnikow** [comment]
You're right. I'm looking into this. (Belatedly!)

It seems that they're both needed to run `./autogen.sh`, which is required for installs from git though not the release tarballs. I'm going to experiment a bit to see if I can get that to work. Fewer install dependencies is a plus.

**Comment by paulmelnikow** [comment]
Addressed in 0e8d4fb. Will defer switching to tarballs to a later date. At this point I'd be lucky to get the module map checked into libbson. If I have to maintain a fork just to ship the module map, I need to make that process as streamlined as possible, and building tarballs seems like extra work. Thank you again.

**Comment by richardcrichardc** [comment]
Thanks Paul!
